### php - service

apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: NodePort
  selector:
    app: php
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010

---

### mysql - service

apiVersion: v1 
kind: Service
metadata:
  name: mysql-connection
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  clusterIP: None


