### Persistent Volume

apiVersion: v1 
kind: PersistentVolume
metadata:
  name: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /meubanco/

---

### Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
    accessModes:
      - ReadWriteMany

